---
- name: Create a new proxy
  hosts: localhost
  tasks:
    - name: Create a new proxy
      ibm.isam.isam:
        log: "{{ _log_ }}"
        force: "{{ force }}"
        action: ibmsecurity.isam.web.reverse_proxy.instance.add
        isamapi:
          inst_name: "{{ inst_name }}"
          host: "{{ host }}"
          listening_port: "{{ listening_port }}"
          domain: "{{ domain }}"
          admin_id: "{{ admin_id }}"
          admin_pwd: "{{ _admin_pwd_ }}"
          ssl_yn: "{{ ssl_yn }}"
          key_file: "{{ key_file }}"
          cert_label: "{{ cert_label }}"
          ssl_port: "{{ ssl_port }}"