---
- name: Create Simple Web Gateway in DataPower
  hosts: localhost
  gather_facts: false
  vars:
    datapower_host: "150.240.162.117"
    datapower_user: "admin"
    datapower_password: "password4datapower"
    gateway_name: "test-web-gateway"
    gateway_domain: "default"
    gateway_port: 8080
    backend_url: "http://example.com:8080"

  tasks:
    - name: Check DataPower connectivity
      uri:
        url: "https://{{ datapower_host }}:9090/service/mgmt/current"
        method: GET
        user: "{{ datapower_user }}"
        password: "{{ datapower_password }}"
        validate_certs: false
        timeout: 60
        status_code: 200
      register: connectivity_check

    - name: Create WebServiceGateway
      uri:
        url: "https://{{ datapower_host }}:9090/service/mgmt/current/config/WebServiceGateway"
        method: POST
        user: "{{ datapower_user }}"
        password: "{{ datapower_password }}"
        validate_certs: false
        timeout: 60
        headers:
          Content-Type: "application/xml"
        body: |
          <?xml version="1.0" encoding="UTF-8"?>
          <WebServiceGateway name="test-web-gateway" domain="default">
            <mAdminState>enabled</mAdminState>
            <mLocalAddress>0.0.0.0</mLocalAddress>
            <mLocalPort>8080</mLocalPort>
            <mRequestType>http</mRequestType>
            <mResponseType>http</mResponseType>
            <mLoggingLevel>info</mLoggingLevel>
            <mLoggingFormat>standard</mLoggingFormat>
            <mBackendURL>http://example.com:8080</mBackendURL>
            <mBackendTimeout>30</mBackendTimeout>
          </WebServiceGateway>
        status_code: [200, 201, 409]
      register: gateway_creation
      failed_when: false

    - name: Display creation result
      debug:
        msg: |
          WebServiceGateway Creation Result:
          Status: {{ gateway_creation.status }}
          {% if gateway_creation.failed %}
          Error: {{ gateway_creation.msg }}
          Response: {{ gateway_creation.content }}
          {% endif %}

    - name: Verify gateway exists
      uri:
        url: "https://{{ datapower_host }}:9090/service/mgmt/current/config/WebServiceGateway/test-web-gateway"
        method: GET
        user: "{{ datapower_user }}"
        password: "{{ datapower_password }}"
        validate_certs: false
        timeout: 60
        status_code: [200, 404]
      register: gateway_verification
      failed_when: false

    - name: Display verification result
      debug:
        msg: |
          Gateway Verification:
          Status: {{ gateway_verification.status }}
          {% if gateway_verification.status == 200 %}
          ✓ Gateway 'test-web-gateway' created successfully
          {% else %}
          ✗ Gateway 'test-web-gateway' not found
          {% endif %}

    - name: Check operational namespace
      uri:
        url: "https://{{ datapower_host }}:9090/service/mgmt/current/WebServiceGateway"
        method: GET
        user: "{{ datapower_user }}"
        password: "{{ datapower_password }}"
        validate_certs: false
        timeout: 60
        status_code: [200, 404]
      register: operational_check
      failed_when: false

    - name: Display operational check
      debug:
        msg: |
          Operational Namespace Check:
          Status: {{ operational_check.status }}
          {% if operational_check.status == 200 %}
          Content: {{ operational_check.content }}
          {% endif %}

    - name: Summary
      debug:
        msg: |
          ===========================================
          Web Gateway Creation Summary
          ===========================================
          Gateway Name: test-web-gateway
          Domain: default
          Port: 8080
          Backend: http://example.com:8080
          
          Creation Status: {{ gateway_creation.status }}
          Verification Status: {{ gateway_verification.status }}
          Operational Status: {{ operational_check.status }}
          
          Next Steps:
          1. Check DataPower UI at https://150.240.162.117:9090
          2. Login with admin/password4datapower
          3. Look in Services section for WebServiceGateway
          4. Check the 'default' domain
          5. Look for 'test-web-gateway'
          ===========================================
